// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/messages/send": {
            "post": {
                "description": "Отправляет сообщение пользователю с заданными полями",
                "tags": [
                    "Notify"
                ],
                "summary": "Отправка сообщения",
                "responses": {
                    "200": {
                        "description": "success"
                    },
                    "500": {
                        "description": "Не удалось создать нотификацию"
                    },
                    "504": {
                        "description": "Время ожидания вышло"
                    }
                }
            }
        },
        "/user/preferences": {
            "put": {
                "description": "Изменяет предпочтения пользователя",
                "tags": [
                    "Preferences"
                ],
                "summary": "Изменение предпочтений",
                "responses": {
                    "200": {
                        "description": "success"
                    },
                    "500": {
                        "description": "Не удалось изменить предпочтения"
                    },
                    "504": {
                        "description": "Время ожидания вышло"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Notify Service",
	Description:      "Notification Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
